
attribute_names = ['name',
                 'latin_name',
                 'is_tree',
                 'is_grass',
                 'is_creeper',
                 'is_swamp_plant',
                 'has_flowers',
                 'has_single_flowers',
                 'has_florets',
                 'flowers_blue',
                 'flowers_red',
                 'flowers_yellow',
                 'flowers_white',
                 'other_colour',
                 'stem_smooth',
                 'stem_rough',
                 'is_creeping',
                 'is_short',
                 'is_medium_tall',
                 'is_tall',
                 'smells_good',
                 'smells_bad',
                 'smells_mildly',
                 'leaves_whole',
                 'leaves_lobed',
                 'leaves_divided',
                 'leaves_dissected',
                 'leaves_margins_entire',
                 'leaves_margins_serrate',
                 'leaves_margins_undulate',
                 'leaves_margins_lobed',
                 'venation_parallel',
                 'venation_palmated',
                 'venation_pinnately_net',
                 'stem_opposite',
                 'stem_alternate',
                 'stem_whorled'
                 'no_stem_arrangement',
                 'is_invasive',
                 'is_eu_invasive',
                 'image_link',
                 'description']
questions_to_index = {i:x for i,x in enumerate(attribute_names[2:-4])}
feature_names = attribute_names[2:-4]
class_to_target = {i+1:name for i,name in enumerate(['oak','maple','birch','jug','ryabina'])}


